/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Standard = {
  _id: string;
  _type: "standard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  nameEng?: string;
  code?: string;
  standardPdf?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  nameEng?: string;
  partnerLogo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEng?: string;
  thumbnailUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: {
    type?: string;
    content?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "normal"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }
    >;
  };
  contentEng?: {
    type?: string;
    content?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            | "normal"
            | "h1"
            | "h2"
            | "h3"
            | "h4"
            | "h5"
            | "h6"
            | "blockquote";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }
    >;
  };
  publishedAt?: string;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEng?: string;
  thumbnailUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: string;
  contentEng?: string;
  publishedAt?: string;
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleEng?: string;
  subTitle?: string;
  subTitleEng?: string;
  description?: string;
  descriptionEng?: string;
  bannerUrl?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Standard
  | Partner
  | SanityImageCrop
  | SanityImageHotspot
  | Article
  | News
  | Banner
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/lib/sanity/queries/banner.ts
// Variable: ALL_BANNERS_QUERY
// Query: *[  _type == "banner"] | order(publishedAt desc) {  _id,  title,  titleEng,  subTitle,  subTitleEng,  description,  descriptionEng,  publishedAt,  "bannerUrl": bannerUrl{    asset->{      _id,      url    },  }}
export type ALL_BANNERS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  titleEng: string | null;
  subTitle: string | null;
  subTitleEng: string | null;
  description: string | null;
  descriptionEng: string | null;
  publishedAt: string | null;
  bannerUrl: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Source: ./src/lib/sanity/queries/news.ts
// Variable: ALL_NEWS_QUERY
// Query: *[  _type == "news"] | order(publishedAt asc) {  _id,  title,  titleEng,  content,  contentEng,  publishedAt,  "thumbnailUrl": thumbnailUrl{    asset->{      _id,      url    },  }}
export type ALL_NEWS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  titleEng: string | null;
  content: string | null;
  contentEng: string | null;
  publishedAt: string | null;
  thumbnailUrl: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: NEWS_QUERY_BY_ID
// Query: *[  _type == "news"  && _id == $_id][0] {  "_id": _id,  title,  titleEng,  content,  contentEng,  publishedAt,  "thumbnailUrl": thumbnailUrl{    asset->{      _id,      url    },  }}
export type NEWS_QUERY_BY_IDResult = {
  _id: string;
  title: string | null;
  titleEng: string | null;
  content: string | null;
  contentEng: string | null;
  publishedAt: string | null;
  thumbnailUrl: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
} | null;
// Variable: ALL_ARTICLE_QUERY
// Query: *[  _type == "news"] | order(publishedAt desc) {  _id,  title,  titleEng,  content,  contentEng,  publishedAt,  "thumbnailUrl": thumbnailUrl{    asset->{      _id,      url    },    hotspot  }}
export type ALL_ARTICLE_QUERYResult = Array<{
  _id: string;
  title: string | null;
  titleEng: string | null;
  content: string | null;
  contentEng: string | null;
  publishedAt: string | null;
  thumbnailUrl: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;

// Source: ./src/lib/sanity/queries/partners.ts
// Variable: ALL_PARTNERS_QUERY
// Query: *[  _type == "partner"] | order(createdAt asc) {  _id,  name,  "partnerLogo": partnerLogo{    asset->{      _id,      url    },  }}
export type ALL_PARTNERS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  partnerLogo: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Source: ./src/lib/sanity/queries/standards.ts
// Variable: ALL_STANDARDS_QUERY
// Query: *[    _type == "standard"    ] | order(cratedAt asc) {    _id,    name,    nameEng,    code,    "standardPdf":standardPdf{        asset->{        _id,        url        }    }}
export type ALL_STANDARDS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  nameEng: string | null;
  code: string | null;
  standardPdf: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "banner"\n] | order(publishedAt desc) {\n  _id,\n  title,\n  titleEng,\n  subTitle,\n  subTitleEng,\n  description,\n  descriptionEng,\n  publishedAt,\n  "bannerUrl": bannerUrl{\n    asset->{\n      _id,\n      url\n    },\n  }\n}': ALL_BANNERS_QUERYResult;
    '*[\n  _type == "news"\n] | order(publishedAt asc) {\n  _id,\n  title,\n  titleEng,\n  content,\n  contentEng,\n  publishedAt,\n  "thumbnailUrl": thumbnailUrl{\n    asset->{\n      _id,\n      url\n    },\n  }\n}': ALL_NEWS_QUERYResult;
    '*[\n  _type == "news"\n  && _id == $_id\n][0] {\n  "_id": _id,\n  title,\n  titleEng,\n  content,\n  contentEng,\n  publishedAt,\n  "thumbnailUrl": thumbnailUrl{\n    asset->{\n      _id,\n      url\n    },\n  }\n}': NEWS_QUERY_BY_IDResult;
    '*[\n  _type == "news"\n] | order(publishedAt desc) {\n  _id,\n  title,\n  titleEng,\n  content,\n  contentEng,\n  publishedAt,\n  "thumbnailUrl": thumbnailUrl{\n    asset->{\n      _id,\n      url\n    },\n    hotspot\n  }\n}': ALL_ARTICLE_QUERYResult;
    '*[\n  _type == "partner"\n] | order(createdAt asc) {\n  _id,\n  name,\n  "partnerLogo": partnerLogo{\n    asset->{\n      _id,\n      url\n    },\n  }\n}': ALL_PARTNERS_QUERYResult;
    '*[\n    _type == "standard"\n    ] | order(cratedAt asc) {\n    _id,\n    name,\n    nameEng,\n    code,\n    "standardPdf":standardPdf{\n        asset->{\n        _id,\n        url\n        }\n    }\n}': ALL_STANDARDS_QUERYResult;
  }
}
